#!/bin/bash
dfu-util -a 1 -d 0x1d50:0x5119 -D image/qi-s3c2442*.udfu
if [ $? -eq 1 ] ; then
dfu-util -a 1 -d 0x1d50:0x5120 -D image/qi-s3c2442*.udfu
dfu-util -a 1 -d 0x1d50:0x5119 -D image/qi-s3c2442*.udfu
fi

